services:
  alist:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5244"
    volumes:
      - "${DATA_PATH}:/opt/alist/data"
      - "${MOUNT_PATH}:/mnt/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - ALIST_ADMIN_PASSWORD=${ALIST_ADMIN_PASSWORD}
    image: ykxvk8yl5l/alist:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true